schema:
  - 'http://localhost:3001/graphql'
documents:
  - './src/graphql/*.graphql'
generates:
  src/generated/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
